### ISSUE TITLE
Include sample charts of BrightEdge data on BrightEdge WDC homepage

### ISSUE THREAD

**Issue by bllevy** [tableau-mkt/brightedge-wdc#2]

**Comment by bllevy** [comment]
@BreezyJ Do you have any vizzes created based on BrightEdge data we could include on the BrightEdge WDC homepage? If not, could you recommend a few views I should put together once a few of these updates get added? 

Thanks!

**Comment by violalee** [comment]
Closing this ticket in 8/30 clean-up session with Josh S.
